# Generated by Django 5.0.1 on 2024-01-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_chairman_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='default.png', upload_to='upload'),
        ),
    ]
