# Generated by Django 5.0.1 on 2024-01-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_member_familyno_member_occupation_member_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pic', models.FileField(blank=True, null=True, upload_to='upload')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='noticeclip')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
