# Generated by Django 5.0.1 on 2024-01-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='video',
        ),
    ]
