# Generated by Django 5.0.1 on 2024-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_notice_pic_remove_notice_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='notice',
            name='name',
            field=models.CharField(default='Tirth', max_length=20),
            preserve_default=False,
        ),
    ]
