# Generated by Django 5.0.1 on 2024-01-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_description_notice_text_notice_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
